services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    restart: on-failure
    expose:
      - 8000
    networks:
      - app-network
    secrets:
      - db-password
    env_file: ./web/.env.prod
    environment:
      DB_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - ./web/staticfiles:/app/staticfiles
      - ./web/mediafiles:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file: ./web/.env.prod
    secrets:
      - db-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      PGDATA: /var/lib/postgresql/data/pgdata
    user: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - app-network
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    command: nginx -g 'daemon off;'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1337:80
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:

secrets:
  db-password:
    file: ./secrets/db/password.txt
